stages:
  make_dataset:
    cmd: python src/make_dataset.py
    deps:
    - src/make_dataset.py
    - ${common.raw_data_path}
    params:
    - common
    - split
    outs:
    - ${common.split_data_path}

  train:
    cmd: python src/train_model.py
    deps:
    - src/train_model.py
    - ${train.data_path}
    - ${eval.data_path}
    params:
    - common
    - model
    - train
    - eval
    outs:
    - ${model.model_pb_path}
    metrics:
    - ${train.metrics_path}
    plots:
    - ${train.loss_plot_path}
    - ${train.accuracy_plot_path}
