stages:
  make_dataset:
    cmd: python src/make_dataset.py
    deps:
    - src/make_dataset.py
    - ${common.raw_data_path}
    params:
    - common
    - split
    outs:
    - ${common.split_data_path}
