common:
  seed: 1337
  raw_data_path: data/raw_data/
  split_data_path: data/split_data/
  metrics_path: metrics/
  plots_path: plots/

split:
  train_split: 0.6
  validation_split: 0.2
  test_split: 0.2
  metrics_path: metrics/metrics_dataset.json

train:
  image_size:
  - 224
  - 224
  epochs: 10
  batch_size: 8
  learning_rate: 0.01
  data_path: data/split_data/train/
  model_pb_path: models/pb/
  metrics_path: metrics/metrics_train.json
  loss_plot_path: plots/model_loss.png
  accuracy_plot_path: plots/model_accuracy.png


eval:
  data_path: data/split_data/val/